import socket
server = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
server.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1)
server.bind((socket.gethostname(),2233))
print("Waiting for connection...")
client, addr = server.recvfrom(1024)
data = client.decode()
split = data.split()
a = int(split[0])
b = int(split[1])
print("6388014: server received from: ",str(addr)," with data ",str(data))
sendtoclient = str(a + b )
server.sendto(sendtoclient.encode(), addr)
server.close()